import { RadicalSchema, type Radical } from "./schema";

/**
 * Curated beginner seed of high-frequency meaning components.
 * Pedagogical order — not Kangxi radical index order.
 * Prefer functional components useful for early recognition.
 */
const seedRaw: Radical[] = [
  {
    id: "person",
    forms: ["人", "亻"],
    gloss: "person; people",
    pinyin: "rén",
    variantsNote: "Standalone 人; left-side combining form 亻.",
    examples: [
      { char: "你", pinyin: "nǐ", gloss: "you" },
      { char: "他", pinyin: "tā", gloss: "he; him" },
      { char: "休", pinyin: "xiū", gloss: "rest" },
    ],
    order: 1,
  },
  {
    id: "water",
    forms: ["水", "氵"],
    gloss: "water; liquid",
    pinyin: "shuǐ",
    variantsNote: "Standalone 水; left-side three-dot form 氵 in compounds.",
    examples: [
      { char: "河", pinyin: "hé", gloss: "river" },
      { char: "海", pinyin: "hǎi", gloss: "sea" },
      { char: "洗", pinyin: "xǐ", gloss: "wash" },
    ],
    order: 2,
  },
  {
    id: "heart",
    forms: ["心", "忄"],
    gloss: "heart; mind; feeling",
    pinyin: "xīn",
    variantsNote: "Standalone or bottom 心; left-side vertical form 忄.",
    examples: [
      { char: "想", pinyin: "xiǎng", gloss: "think; want" },
      { char: "忙", pinyin: "máng", gloss: "busy" },
      { char: "情", pinyin: "qíng", gloss: "feeling; emotion" },
    ],
    order: 3,
  },
  {
    id: "hand",
    forms: ["手", "扌"],
    gloss: "hand; action with the hand",
    pinyin: "shǒu",
    variantsNote: "Standalone 手; left-side combining form 扌.",
    examples: [
      { char: "打", pinyin: "dǎ", gloss: "hit; dial" },
      { char: "找", pinyin: "zhǎo", gloss: "look for" },
      { char: "拿", pinyin: "ná", gloss: "take; hold" },
    ],
    order: 4,
  },
  {
    id: "mouth",
    forms: ["口"],
    gloss: "mouth; opening; speech-related",
    pinyin: "kǒu",
    examples: [
      { char: "吃", pinyin: "chī", gloss: "eat" },
      { char: "叫", pinyin: "jiào", gloss: "call; be called" },
      { char: "名", pinyin: "míng", gloss: "name" },
    ],
    order: 5,
  },
  {
    id: "speech",
    forms: ["言", "讠"],
    gloss: "speech; words",
    pinyin: "yán",
    variantsNote: "Standalone/full form 言; simplified left-side combining form 讠.",
    examples: [
      { char: "说", pinyin: "shuō", gloss: "speak; say" },
      { char: "话", pinyin: "huà", gloss: "speech; words" },
      { char: "请", pinyin: "qǐng", gloss: "please; invite" },
    ],
    order: 6,
  },
  {
    id: "woman",
    forms: ["女"],
    gloss: "woman; female",
    pinyin: "nǚ",
    examples: [
      { char: "妈", pinyin: "mā", gloss: "mom" },
      { char: "好", pinyin: "hǎo", gloss: "good" },
      { char: "她", pinyin: "tā", gloss: "she; her" },
    ],
    order: 7,
  },
  {
    id: "wood",
    forms: ["木"],
    gloss: "wood; tree; plant-related",
    pinyin: "mù",
    examples: [
      { char: "林", pinyin: "lín", gloss: "woods; forest" },
      { char: "机", pinyin: "jī", gloss: "machine" },
      { char: "休", pinyin: "xiū", gloss: "rest" },
    ],
    order: 8,
  },
  {
    id: "fire",
    forms: ["火", "灬"],
    gloss: "fire; heat",
    pinyin: "huǒ",
    variantsNote: "Standalone or left 火; four-dot bottom form 灬.",
    examples: [
      { char: "热", pinyin: "rè", gloss: "hot" },
      { char: "烧", pinyin: "shāo", gloss: "burn; cook" },
      { char: "灯", pinyin: "dēng", gloss: "lamp" },
    ],
    order: 9,
  },
  {
    id: "earth",
    forms: ["土"],
    gloss: "earth; soil; ground",
    pinyin: "tǔ",
    examples: [
      { char: "地", pinyin: "dì", gloss: "ground; place" },
      { char: "坐", pinyin: "zuò", gloss: "sit" },
      { char: "城", pinyin: "chéng", gloss: "city; wall" },
    ],
    order: 10,
  },
  {
    id: "sun",
    forms: ["日"],
    gloss: "sun; day; time of day",
    pinyin: "rì",
    examples: [
      { char: "明", pinyin: "míng", gloss: "bright; tomorrow" },
      { char: "时", pinyin: "shí", gloss: "time" },
      { char: "早", pinyin: "zǎo", gloss: "early; morning" },
    ],
    order: 11,
  },
  {
    id: "moon",
    forms: ["月"],
    gloss: "moon; month; often flesh/body in compounds",
    pinyin: "yuè",
    variantsNote: "As a radical, 月 often marks body parts (historically from 肉).",
    examples: [
      { char: "明", pinyin: "míng", gloss: "bright" },
      { char: "朋", pinyin: "péng", gloss: "friend" },
      { char: "脑", pinyin: "nǎo", gloss: "brain" },
    ],
    order: 12,
  },
  {
    id: "mountain",
    forms: ["山"],
    gloss: "mountain; hill",
    pinyin: "shān",
    examples: [
      { char: "岛", pinyin: "dǎo", gloss: "island" },
      { char: "岸", pinyin: "àn", gloss: "shore; bank" },
      { char: "峰", pinyin: "fēng", gloss: "peak" },
    ],
    order: 13,
  },
  {
    id: "grass",
    forms: ["艹"],
    gloss: "grass; plants",
    pinyin: "cǎo",
    variantsNote: "Top grass radical 艹 (from 艸); common in plant names.",
    examples: [
      { char: "花", pinyin: "huā", gloss: "flower" },
      { char: "茶", pinyin: "chá", gloss: "tea" },
      { char: "草", pinyin: "cǎo", gloss: "grass" },
    ],
    order: 14,
  },
  {
    id: "bamboo",
    forms: ["竹", "⺮"],
    gloss: "bamboo",
    pinyin: "zhú",
    variantsNote: "Standalone 竹; top combining form ⺮.",
    examples: [
      { char: "笔", pinyin: "bǐ", gloss: "pen; writing brush" },
      { char: "笑", pinyin: "xiào", gloss: "laugh; smile" },
      { char: "第", pinyin: "dì", gloss: "ordinal prefix" },
    ],
    order: 15,
  },
  {
    id: "silk",
    forms: ["糸", "纟"],
    gloss: "silk; thread; textile",
    pinyin: "mì",
    variantsNote: "Full form 糸; simplified left-side 纟.",
    examples: [
      { char: "红", pinyin: "hóng", gloss: "red" },
      { char: "给", pinyin: "gěi", gloss: "give; for" },
      { char: "纸", pinyin: "zhǐ", gloss: "paper" },
    ],
    order: 16,
  },
  {
    id: "metal",
    forms: ["金", "钅"],
    gloss: "metal; gold; money-related tools",
    pinyin: "jīn",
    variantsNote: "Standalone 金; left-side simplified 钅.",
    examples: [
      { char: "钱", pinyin: "qián", gloss: "money" },
      { char: "银", pinyin: "yín", gloss: "silver" },
      { char: "针", pinyin: "zhēn", gloss: "needle" },
    ],
    order: 17,
  },
  {
    id: "door",
    forms: ["门"],
    gloss: "door; gate",
    pinyin: "mén",
    examples: [
      { char: "问", pinyin: "wèn", gloss: "ask" },
      { char: "间", pinyin: "jiān", gloss: "between; room" },
      { char: "闻", pinyin: "wén", gloss: "hear; smell; news" },
    ],
    order: 18,
  },
  {
    id: "rain",
    forms: ["雨"],
    gloss: "rain; weather from the sky",
    pinyin: "yǔ",
    examples: [
      { char: "雪", pinyin: "xuě", gloss: "snow" },
      { char: "雷", pinyin: "léi", gloss: "thunder" },
      { char: "零", pinyin: "líng", gloss: "zero; leftover" },
    ],
    order: 19,
  },
  {
    id: "stone",
    forms: ["石"],
    gloss: "stone; rock",
    pinyin: "shí",
    examples: [
      { char: "硬", pinyin: "yìng", gloss: "hard; stiff" },
      { char: "码", pinyin: "mǎ", gloss: "code; yard" },
      { char: "破", pinyin: "pò", gloss: "break; damaged" },
    ],
    order: 20,
  },
  {
    id: "horse",
    forms: ["马"],
    gloss: "horse",
    pinyin: "mǎ",
    examples: [
      { char: "妈", pinyin: "mā", gloss: "mom" },
      { char: "骑", pinyin: "qí", gloss: "ride" },
      { char: "验", pinyin: "yàn", gloss: "test; verify" },
    ],
    order: 21,
  },
  {
    id: "bird",
    forms: ["鸟"],
    gloss: "bird",
    pinyin: "niǎo",
    examples: [
      { char: "鸡", pinyin: "jī", gloss: "chicken" },
      { char: "鸭", pinyin: "yā", gloss: "duck" },
      { char: "鸣", pinyin: "míng", gloss: "bird call; sound" },
    ],
    order: 22,
  },
  {
    id: "fish",
    forms: ["鱼"],
    gloss: "fish",
    pinyin: "yú",
    examples: [
      { char: "鲜", pinyin: "xiān", gloss: "fresh" },
      { char: "渔", pinyin: "yú", gloss: "fishing" },
      { char: "鲁", pinyin: "lǔ", gloss: "Lu (surname/place)" },
    ],
    order: 23,
  },
  {
    id: "insect",
    forms: ["虫"],
    gloss: "insect; worm; small creature",
    pinyin: "chóng",
    examples: [
      { char: "虽", pinyin: "suī", gloss: "although" },
      { char: "蛇", pinyin: "shé", gloss: "snake" },
      { char: "独", pinyin: "dú", gloss: "alone" },
    ],
    order: 24,
  },
  {
    id: "knife",
    forms: ["刀", "刂"],
    gloss: "knife; cut; blade",
    pinyin: "dāo",
    variantsNote: "Standalone 刀; right-side standing knife 刂.",
    examples: [
      { char: "切", pinyin: "qiē", gloss: "cut" },
      { char: "别", pinyin: "bié", gloss: "don't; other" },
      { char: "到", pinyin: "dào", gloss: "arrive; to" },
    ],
    order: 25,
  },
  {
    id: "strength",
    forms: ["力"],
    gloss: "strength; power; force",
    pinyin: "lì",
    examples: [
      { char: "男", pinyin: "nán", gloss: "man; male" },
      { char: "动", pinyin: "dòng", gloss: "move" },
      { char: "功", pinyin: "gōng", gloss: "achievement; skill" },
    ],
    order: 26,
  },
  {
    id: "walk",
    forms: ["走", "辶"],
    gloss: "walk; movement; road-related",
    pinyin: "zǒu",
    variantsNote: "Standalone 走; enclosing walk radical 辶 (simplified).",
    examples: [
      { char: "进", pinyin: "jìn", gloss: "enter; advance" },
      { char: "远", pinyin: "yuǎn", gloss: "far" },
      { char: "道", pinyin: "dào", gloss: "road; way" },
    ],
    order: 27,
  },
  {
    id: "eye",
    forms: ["目"],
    gloss: "eye; seeing",
    pinyin: "mù",
    examples: [
      { char: "看", pinyin: "kàn", gloss: "look; see" },
      { char: "睡", pinyin: "shuì", gloss: "sleep" },
      { char: "眼", pinyin: "yǎn", gloss: "eye" },
    ],
    order: 28,
  },
  {
    id: "ear",
    forms: ["耳"],
    gloss: "ear; hearing",
    pinyin: "ěr",
    examples: [
      { char: "听", pinyin: "tīng", gloss: "listen" },
      { char: "闻", pinyin: "wén", gloss: "hear; news" },
      { char: "取", pinyin: "qǔ", gloss: "take; fetch" },
    ],
    order: 29,
  },
  {
    id: "foot",
    forms: ["足", "⻊"],
    gloss: "foot; leg; enough",
    pinyin: "zú",
    variantsNote: "Standalone 足; left-side combining form ⻊.",
    examples: [
      { char: "跑", pinyin: "pǎo", gloss: "run" },
      { char: "路", pinyin: "lù", gloss: "road" },
      { char: "跟", pinyin: "gēn", gloss: "follow; with" },
    ],
    order: 30,
  },
  {
    id: "clothing",
    forms: ["衣", "衤"],
    gloss: "clothing; garments",
    pinyin: "yī",
    variantsNote: "Standalone 衣; left-side combining form 衤.",
    examples: [
      { char: "裤", pinyin: "qún", gloss: "skirt" },
      { char: "衬", pinyin: "chèn", gloss: "lining; shirt" },
      { char: "袋", pinyin: "dài", gloss: "bag; pocket" },
    ],
    order: 31,
  },
  {
    id: "food",
    forms: ["食", "饣"],
    gloss: "food; eat",
    pinyin: "shí",
    variantsNote: "Standalone 食; left-side simplified 饣.",
    examples: [
      { char: "饭", pinyin: "fàn", gloss: "meal; rice" },
      { char: "饿", pinyin: "è", gloss: "hungry" },
      { char: "馆", pinyin: "guǎn", gloss: "restaurant; hall" },
    ],
    order: 32,
  },
  {
    id: "rice",
    forms: ["米"],
    gloss: "rice; grain",
    pinyin: "mǐ",
    examples: [
      { char: "粉", pinyin: "fěn", gloss: "powder; noodles" },
      { char: "精", pinyin: "jīng", gloss: "essence; refined" },
      { char: "粮", pinyin: "liáng", gloss: "grain; provisions" },
    ],
    order: 33,
  },
  {
    id: "field",
    forms: ["田"],
    gloss: "field; farmland",
    pinyin: "tián",
    examples: [
      { char: "男", pinyin: "nán", gloss: "man; male" },
      { char: "里", pinyin: "lǐ", gloss: "inside; village" },
      { char: "留", pinyin: "liú", gloss: "stay; leave behind" },
    ],
    order: 34,
  },
  {
    id: "big",
    forms: ["大"],
    gloss: "big; large",
    pinyin: "dà",
    examples: [
      { char: "太", pinyin: "tài", gloss: "too; extremely" },
      { char: "天", pinyin: "tiān", gloss: "sky; day" },
      { char: "美", pinyin: "měi", gloss: "beautiful" },
    ],
    order: 35,
  },
  {
    id: "small",
    forms: ["小"],
    gloss: "small; little",
    pinyin: "xiǎo",
    examples: [
      { char: "少", pinyin: "shǎo", gloss: "few; less" },
      { char: "尖", pinyin: "jiān", gloss: "pointed; sharp" },
      { char: "当", pinyin: "dāng", gloss: "act as; when" },
    ],
    order: 36,
  },
  {
    id: "child",
    forms: ["子"],
    gloss: "child; son; small thing",
    pinyin: "zǐ",
    examples: [
      { char: "字", pinyin: "zì", gloss: "character; word" },
      { char: "学", pinyin: "xué", gloss: "study; learn" },
      { char: "好", pinyin: "hǎo", gloss: "good" },
    ],
    order: 37,
  },
  {
    id: "jade",
    forms: ["玉", "王"],
    gloss: "jade; precious; king-form as left radical",
    pinyin: "yù",
    variantsNote: "As a left radical, 玉 usually appears as 王 (king form) plus a dot in full 玉.",
    examples: [
      { char: "现", pinyin: "xiàn", gloss: "appear; now" },
      { char: "球", pinyin: "qiú", gloss: "ball" },
      { char: "玩", pinyin: "wán", gloss: "play" },
    ],
    order: 38,
  },
  {
    id: "illness",
    forms: ["疒"],
    gloss: "illness; disease",
    pinyin: "nè",
    variantsNote: "Sickness enclosure radical 疒.",
    examples: [
      { char: "病", pinyin: "bìng", gloss: "illness; sick" },
      { char: "痛", pinyin: "tòng", gloss: "pain; ache" },
      { char: "疲", pinyin: "pí", gloss: "tired" },
    ],
    order: 39,
  },
  {
    id: "roof",
    forms: ["宀"],
    gloss: "roof; building; house",
    pinyin: "mián",
    variantsNote: "Top roof radical 宀.",
    examples: [
      { char: "家", pinyin: "jiā", gloss: "home; family" },
      { char: "安", pinyin: "ān", gloss: "safe; peaceful" },
      { char: "字", pinyin: "zì", gloss: "character" },
    ],
    order: 40,
  },
  {
    id: "shell",
    forms: ["贝"],
    gloss: "shell; money; valuables",
    pinyin: "bèi",
    examples: [
      { char: "贵", pinyin: "guì", gloss: "expensive; noble" },
      { char: "买", pinyin: "mǎi", gloss: "buy" },
      { char: "货", pinyin: "huò", gloss: "goods" },
    ],
    order: 41,
  },
  {
    id: "vehicle",
    forms: ["车"],
    gloss: "vehicle; cart",
    pinyin: "chē",
    examples: [
      { char: "辆", pinyin: "liàng", gloss: "measure word for vehicles" },
      { char: "轻", pinyin: "qīng", gloss: "light; gentle" },
      { char: "转", pinyin: "zhuǎn", gloss: "turn; transfer" },
    ],
    order: 42,
  },
  {
    id: "ice",
    forms: ["冫"],
    gloss: "ice; cold",
    pinyin: "bīng",
    variantsNote: "Two-dot ice radical 冫 (related to 冰).",
    examples: [
      { char: "冷", pinyin: "lěng", gloss: "cold" },
      { char: "次", pinyin: "cì", gloss: "time; sequence" },
      { char: "准", pinyin: "zhǔn", gloss: "accurate; prepare" },
    ],
    order: 43,
  },
  {
    id: "enclosure",
    forms: ["囗"],
    gloss: "enclosure; surrounding border",
    pinyin: "wéi",
    variantsNote: "Larger box 囗 (distinct from mouth 口).",
    examples: [
      { char: "国", pinyin: "guó", gloss: "country" },
      { char: "回", pinyin: "huí", gloss: "return" },
      { char: "图", pinyin: "tú", gloss: "map; diagram" },
    ],
    order: 44,
  },
  {
    id: "cliff",
    forms: ["厂"],
    gloss: "cliff; factory/building shorthand",
    pinyin: "hǎn",
    variantsNote: "Cliff radical 厂; also appears in 厂 (chǎng, factory).",
    examples: [
      { char: "厅", pinyin: "tīng", gloss: "hall" },
      { char: "历", pinyin: "lì", gloss: "history; calendar" },
      { char: "原", pinyin: "yuán", gloss: "original; plain" },
    ],
    order: 45,
  },
];

/** Validated, ordered seed set shipped with the app. */
export const RADICALS: Radical[] = RadicalSchema.array()
  .min(30)
  .max(50)
  .parse(seedRaw)
  .slice()
  .sort((a, b) => a.order - b.order);
